# Generated by Django 5.2.4 on 2025-07-06 22:41

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='dados',
        ),
        migrations.AddField(
            model_name='entidade',
            name='nome',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='entidade',
            name='valores_campos',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='campanhas.categoria'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('checkbox', 'Checkbox'), ('textarea', 'Texto Longo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='campanhas.campanha'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='campanhas.categoria'),
        ),
    ]
