# Generated by Django 5.2.4 on 2025-07-06 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_remove_entidade_dados_entidade_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='entidade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
